networks:
  laravel:
    driver: bridge

services:
  proxy:
    image: dommin/store-proxy:${IMAGE_TAG}
    container_name: ${DOCKER_PREFIX}_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - frontend
      - nginx
    networks:
      - laravel

  frontend:
    image: dommin/store-frontend:${IMAGE_TAG}
    container_name: ${DOCKER_PREFIX}_frontend
    restart: unless-stopped
    command: sh -c "npm run start"
    depends_on:
      - api
    networks:
      - laravel

  api:
    image: dommin/store-api:${IMAGE_TAG}
    container_name: ${DOCKER_PREFIX}_api
    command: php-fpm
    restart: unless-stopped
    volumes:
      - type: volume
        source: storage
        target: /usr/src/storage
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - laravel

  scheduler:
    image: dommin/store-scheduler:${IMAGE_TAG}
    container_name: ${DOCKER_PREFIX}_scheduler
    restart: unless-stopped
    command: sh -c "chmod +x /usr/src/scheduler.sh && /usr/src/scheduler.sh"
    volumes:
      - type: volume
        source: storage
        target: /usr/src/storage
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - laravel

  worker:
    image: dommin/store-worker:${IMAGE_TAG}
    container_name: ${DOCKER_PREFIX}_worker
    restart: unless-stopped
    command: sh -c "chmod +x /usr/src/worker.sh && /usr/src/worker.sh"
    volumes:
      - type: volume
        source: storage
        target: /usr/src/storage
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - laravel

  nginx:
    image: dommin/store-nginx:${IMAGE_TAG}
    container_name: ${DOCKER_PREFIX}_nginx
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - laravel

  mysql:
    image: dommin/store-mysql:${IMAGE_TAG}
    container_name: ${DOCKER_PREFIX}_mysql
    restart: unless-stopped
    healthcheck:
      test: mysql -h localhost -u root -p${DB_PASSWORD} -e 'SELECT version();'
      start_period: 5s
      interval: 15s
      timeout: 5s
      retries: 5
    volumes:
      - type: volume
        source: mysqldata
        target: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: ${DOCKER_PREFIX}_redis
    restart: unless-stopped
    command: redis-server --maxmemory 128mb --maxmemory-policy volatile-lru --save ""
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - type: volume
        source: redisdata
        target: /data
    networks:
      - laravel

  watchtower:
    image: containrrr/watchtower:1.5.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REPO_USER=${DOCKERHUB_USERNAME}
      - REPO_PASS=${DOCKERHUB_PASSWORD}
    networks:
      - laravel

volumes:
  storage:
  mysqldata:
  redisdata:
