# Stage 1: Build the API image
FROM dunglas/frankenphp AS api

ENV SERVER_NAME="http://"

# Install necessary dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    autoconf \
    gcc \
    g++ \
    make \
    libpcre3-dev \
    zlib1g-dev \
    file \
    bash \
    linux-headers-amd64 \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    libicu-dev \
    libc6-dev \
    zip \
    unzip \
    supervisor \
    default-mysql-client \
    libmagickwand-dev \
    libtool \
    nodejs \
    npm \
    libbrotli-dev

RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip intl \
&& pecl install redis xdebug imagick swoole \
&& docker-php-ext-enable imagick \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /usr/src

# Copy PHP configuration
COPY ./deployment/config/php-fpm/php-prod.ini /usr/local/etc/php/conf.d/php.ini
COPY ./deployment/config/php-fpm/www.conf /usr/local/etc/php-fpm.d/www.conf

# Copy application files
COPY ./api ./

# Install application dependencies
RUN composer install --prefer-dist --no-scripts --no-progress --no-suggest \
    && npm install --no-progress

# Ensure correct permissions
RUN chown -R www-data:www-data /usr/src && \
    chmod -R 775 ./storage ./bootstrap/cache

# Copy Supervisor configuration for Octane
COPY ./deployment/config/supervisor/octane/dev/supervisord.conf /etc/supervisor/conf.d/octane_supervisor.conf

ENV FRANKENPHP_CONFIG="worker ./public/index.php"

# Stage 2: Build the Worker image
FROM api AS worker
COPY ./deployment/config/supervisor/worker/supervisord.conf /etc/supervisor/conf.d/worker_supervisor.conf
CMD ["/bin/sh", "/usr/src/worker.sh"]

# Stage 3: Build the Scheduler image
FROM api AS scheduler
CMD ["/bin/sh", "/usr/src/scheduler.sh"]

# Stage 4: Build the Reverb image
FROM api AS reverb
COPY ./deployment/config/supervisor/reverb/supervisord.conf /etc/supervisor/conf.d/reverb_supervisor.conf
CMD ["/bin/sh", "/usr/src/reverb.sh"]
