FROM node:18-alpine AS base

WORKDIR /usr/src

COPY ./frontend/package*.json ./
RUN npm install --silent

COPY ./frontend .
EXPOSE 3000

FROM base AS dev
EXPOSE 3000

# Build image
FROM base AS build
RUN npm run build

# Production image
FROM node:18-alpine AS prod
COPY --from=build /usr/src /usr/src
WORKDIR /usr/src
EXPOSE 3000
CMD ["npm", "run", "start"]
