# Stage 1: Build the API image
FROM dommin/php-8.2:latest as api

# Copy PHP-FPM configuration
COPY ./deployment/config/php-fpm/php-prod.ini /usr/local/etc/php/conf.d/php.ini
COPY ./deployment/config/php-fpm/www.conf /usr/local/etc/php-fpm.d/www.conf

# Copy application files
COPY ./api/worker.sh ./api/reverb.sh ./api/scheduler.sh ./api/migration.sh ./
COPY ./api ./

# Install application dependencies
RUN composer install --prefer-dist --no-scripts --no-progress --no-suggest --optimize-autoloader
RUN npm install

RUN chown -R www-data:www-data /usr/src && \
    chmod -R 775 ./storage ./bootstrap/cache
    
COPY ./deployment/config/supervisor/octane/dev/supervisord.conf /etc/supervisor/conf.d/octane_supervisor.conf

# Stage 2: Build the Worker image
FROM api AS worker
COPY ./deployment/config/supervisor/worker/supervisord.conf /etc/supervisor/conf.d/worker_supervisor.conf
CMD ["/bin/sh", "/usr/src/worker.sh"]

# Stage 3: Build the Scheduler image
FROM api AS scheduler
CMD ["/bin/sh", "/usr/src/scheduler.sh"]

# Stage 4: Build the Reverb image
FROM api AS reverb
COPY ./deployment/config/supervisor/reverb/supervisord.conf /etc/supervisor/conf.d/reverb_supervisor.conf
CMD ["/bin/sh", "/usr/src/reverb.sh"]
