name: Tests

on:
  push:
    branches: [ "main" ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql # Add the extensions you need
          coverage: none
      - name: Install Dependencies
        run: |
          cd api
          composer install --prefer-dist --no-progress
      - name: Run phpstan
        run: |
          cd api
          ./vendor/bin/phpstan analyze --memory-limit=1G
      - name: Run phpinsights
        run: |
          cd api
          php artisan insights --no-interaction --min-quality=90 --min-complexity=80 --min-architecture=90 --min-style=90 --ansi --format=github-action

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql
          coverage: none
      - name: Install Dependencies
        run: |
          cd api
          composer install --prefer-dist --no-progress
      - name: Run tests
        run: |
          cd api
          composer pest
