name: Deploy to DigitalOcean

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Copy .env
        run: |
          cd api
          cp .env.example .env
      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      - name: Login to DigitalOcean
        run: |
          echo ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} | doctl auth login --context main --token-stdin

      - name: Pull Docker images from Docker Hub
        run: |
          doctl kubernetes cluster kubeconfig save my-cluster
          kubectl config use-context do-my-cluster
          kubectl apply -f kubernetes/deployment.yaml
