name: Tests

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql # Add the extensions you need
          coverage: none
      - name: Install Dependencies
        run: |
          cd api
          composer install --prefer-dist --no-progress
      - name: Run phpinsights
        run: |
          cd api
          php artisan insights --no-interaction --min-quality=90 --min-complexity=90 --min-architecture=90 --min-style=90 --ansi --format=github-action

  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: laravel-testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: Copy .env.testing
        run: |
          cd api
          cp .env.testing .env
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql
          coverage: none
      - name: Install Dependencies
        run: |
          cd api
          composer install --prefer-dist --no-progress
      - name: Generate key
        run: |
          cd api 
          php artisan key:generate
      - name: Run migrations
        run: |
          cd api
          php artisan migrate
      - name: Run tests
        run: |
          cd api
          composer pest
