name: Deploy to DigitalOcean

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install doctl
        run: |
          mkdir -p /home/runner/doctl
          curl -sL https://github.com/digitalocean/doctl/releases/download/v1.63.0/doctl-1.63.0-linux-amd64.tar.gz | tar -xzv -C /home/runner/doctl
          sudo mv /home/runner/doctl/doctl /usr/local/bin/doctl

      - name: Copy .env
        run: |
          cd api
          cp .env.example .env

      - name: Build and push Docker images
        run: |
          docker-compose build
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker-compose push

      - name: Login to DigitalOcean
        run: |
          doctl auth init --access-token "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}"

      - name: Copy project files to DigitalOcean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_SSH_PASSWORD }}
          source: "."
          target: "/home/${{ secrets.DROPLET_USERNAME }}/project"

      - name: SSH into DigitalOcean Droplet and run Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.DROPLET_USERNAME }}/project
            docker-compose up -d
